### ISSUE TITLE
class-wp-hook.php error

### ISSUE THREAD

**Issue by dzogbenyui-agblevon** [oceanwp/oceanwp#480]
Greetings dear team,
While trying to go to Customizer, I encountered this error message : 

`Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "wp_print_media_templates" not found or invalid function name in C:\xampp\htdocs\educonsulting\wp-includes\class-wp-hook.php:324 Stack trace: #0 C:\xampp\htdocs\educonsulting\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #1 C:\xampp\htdocs\educonsulting\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #2 C:\xampp\htdocs\educonsulting\wp-includes\script-loader.php(2248): do_action('wp_print_footer...') #3 C:\xampp\htdocs\educonsulting\wp-includes\block-editor.php(377): wp_print_footer_scripts() #4 C:\xampp\htdocs\educonsulting\wp-includes\block-editor.php(623): _wp_get_iframed_editor_assets() #5 C:\xampp\htdocs\educonsulting\wp-includes\class-wp-customize-widgets.php(848): get_block_editor_settings(Array, Object(WP_Block_Editor_Context)) #6 C:\xampp\htdocs\educonsulting\wp-includes\class-wp-hook.php(324): WP_Customize_Widgets->enqueue_scripts('') #7 C:\xampp\htdocs\educonsulting\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #8 C:\xampp\htdocs\educonsulting\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #9 C:\xampp\htdocs\educonsulting\wp-admin\customize.php(123): do_action('customize_contr...') #10 {main} thrown in C:\xampp\htdocs\educonsulting\wp-includes\class-wp-hook.php on line 324`

I'm using oceanwp 3.5.5

kindly help please

**Comment by skalanter** [comment]
Hello @dzogbenyui-agblevon 

Thank you for reaching out,

We have not received any similar reports so far, and we can not reproduce that issue on our end.

Unfortunately, the information provided in this thread regarding the issue you are having is insufficient for troubleshooting purposes and the possibility of understanding the reason why this is happening on your end.

Kindly share the following info that could help us understand the issue you described better and hopefully help you resolve it:

1. Please tell us how to reproduce the issue So we can recreate it somewhere other than your website(share your steps on a brand-new WordPress).

2. Please provide us with your system environment information. To do this, please go to  WP Dashboard > Tools > Site Health > Info Tab and click on the button Copy site info to clipboard. You can send the information as code here or upload them to http://pastebin.com/ and get an exclusive link: https://i.postimg.cc/fbjtkFyJ/image.png(you can remove your email address from the content).

→ Before sending these, please make sure that:
Everything on your website runs the latest versions (WP, theme, plugins). Then, please perform a basic troubleshooting checkup method and make sure the issue is related to our theme or plugin(s). To do this, deactivate all other plugins. After that, activate them individually and check for this issue. Continue doing this until you find out what product is causing a conflict with our product. Then, could you provide the details as explained above?

**Note:** If you have any cache plugin or server cache(CDN / Browser Cache and Cookies and ...), you need to clear its cache contents or disable them to see your changes.

______________________

Please note that if you have any more questions or want to continue this conversation, please join our Facebook group for support. So you can share the details as explained above on our Facebook support page.
We don’t monitor GitHub for support.

**Facebook Community Support Group:** ​https://www.facebook.com/groups/oceanwptheme/

Please keep us posted.
And thank you for understanding,
Best Regards

**Comment by MarkHollo** [comment]
Since there hasn't been any additional info on this matter, and no similar issue has been reported before/after this GH thread, along with the fact that nothing in the error log has ever indicated a problem tied to OceanWP therefore it was most likely an isolated problem related to the setup, I'm closing this thread.. Further more,  we have also changed all Customizer files since OceanWP 4.0.0 and improved and optimized everything drastically, therefore all further reports on this matter would have been outdated/incorrect.

For tech support, feel free to visit any of the following channels where our team is ready to help you out:

- [WordPress forum](https://wordpress.org/support/theme/oceanwp/), or
- [OceanWP Facebook group](https://www.facebook.com/groups/oceanwptheme).

If you have a premium license, you can always reach us directly via email or [submit a support ticket](https://oceanwp.org/support/).

Cheers!
